version: '3.9'
services:
  spring_mvc:
    image: mysql:latest
    container_name: spring_mvc
    volumes:
      - ./data:/data
    ports:
      - '3306:3306'
    environment:
      - 'POSTGRES_PASSWORD=@root#'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=spring_mvc_hibernate'